[package]
name = "openswap-plugin"
version = "0.1.0"
edition = "2021"
description = "Run openswap maker/taker inside BTCPay Server."
license = "MIT"

[lib]
crate-type = ["cdylib"]
name = "btcpay_plugin_native"

[dependencies]
btcpay-plugin = { git = "https://github.com/uqlidi/btcpay-rs" }

openswap = { git = "https://github.com/citadel-foss/openswap", rev = "6f645621773024835f78260e4f086e970a8b371b" }

log = "0.4"

[profile.release]
lto = true
strip = false
