[package]
name = "coinswap-maker"
version = "0.1.0"
edition = "2021"
description = "Run a coinswap maker inside BTCPay Server."
license = "MIT"

[lib]
crate-type = ["cdylib"]
name = "btcpay_plugin_native"

[dependencies]
btcpay-plugin = { git = "https://github.com/uqlidi/btcpay-rs" }

coinswap = { git = "https://github.com/citadel-tech/coinswap", rev = "20a0421e365d8624eba398da8779d1ad3098b793" }

log = "0.4"

[profile.release]
lto = true
strip = false
